### ISSUE TITLE
The example page  is not working

### ISSUE THREAD

**Issue by vsymguysung** [kpfefferle/liquid-fire-reveal#1]
First, thanks for sharing the transition but I can not see the example.

**Comment by kpfefferle** [comment]
Thanks for letting me know @vsymguysung! I've rolled back the `gh-pages` branch to a working version until I can figure out what went wrong with the newer build. The example page is working again.

**Comment by devinrhode2** [comment]
Looks like it stopped working again, the index.html loads but all the assets fail to load from these paths:
![screen shot 2016-09-25 at 11 43 34 am](https://cloud.githubusercontent.com/assets/539816/18817457/84717794-8315-11e6-8f63-2049ec8a0977.png)
Base tag:`<base href="/liquid-fire-reveal/">` example asset link: `<link rel="stylesheet" href="/assets/vendor-571d67531622102402268bd2c623c17f.css">`

**Comment by kpfefferle** [comment]
@devinrhode2 Thanks for the heads up. It seems that I forgot to update the `rootUrl` during the migration from `baseUrl` to `rootUrl`. I believe that it's working again now.
